import React, { Fragment } from 'react'

import Order from '../../components/Burger/Order/Order'
import axios from '../../axios-order'
import withErrorHandler from '../../hoc/withErrorHandler/withErrorHandler'


class Orders extends React.Component {
    state = {
        orders: [],
        loading: true
    }

    componentDidMount() {
        axios.get('/orders.json')
            .then(res => {
                const fetchedOrders = []
                // key is the unique id generated by the firebase
                for (let key in res.data) {
                    fetchedOrders.push({
                        ...res.data[key],   // this is the data for the particular id
                        id: key             // unique id generated by the firebase
                    })
                }
                this.setState({ loading: false , orders: fetchedOrders})
            })
            .catch(err => {
                this.setState({ loading: false })
            })
    }

    render() {
        return (
            <Fragment>
                {this.state.orders.map(order => (
                    <Order 
                        key={order.id}
                        price={order.price}
                        ingredients={order.ingredients}/>
                ))}
            </Fragment>
        )
    }
}

export default withErrorHandler(Orders, axios)